# Generated by Django 3.0.3 on 2022-09-02 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0004_auto_20220902_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='address',
            new_name='eaddress',
        ),
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='city',
            new_name='ecity',
        ),
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='email',
            new_name='eemail',
        ),
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='name',
            new_name='ename',
        ),
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='phone',
            new_name='ephone',
        ),
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='state',
            new_name='estate',
        ),
        migrations.RemoveField(
            model_name='requestenvelope',
            name='date',
        ),
        migrations.RemoveField(
            model_name='requestenvelope',
            name='sub_group',
        ),
        migrations.AddField(
            model_name='requestenvelope',
            name='esub_group',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='requestdonationbox',
            name='sub_group',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.DeleteModel(
            name='SubscriptionGroup',
        ),
    ]
