# Generated by Django 3.0.3 on 2022-09-01 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='RequestEnvelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonprofit.SubscriptionGroup')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDonationBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('sub_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonprofit.SubscriptionGroup')),
            ],
        ),
    ]
