# Generated by Django 3.0.3 on 2022-09-02 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0003_auto_20220902_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='eaddress',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='ecity',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='edate',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='eemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='ename',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='ephone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='requestenvelope',
            old_name='estate',
            new_name='state',
        ),
    ]
