# Generated by Django 3.0.3 on 2022-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0006_auto_20220902_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingDonation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('state', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('cc', models.CharField(blank=True, max_length=500)),
                ('date', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
