# Generated by Django 3.0.3 on 2022-09-05 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0007_clothingdonation'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingdonation',
            name='time',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='requestdonationbox',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='requestenvelope',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
